<a href="https://colab.research.google.com/github/narsym/deep-learning-with-pytorch/blob/master/pytorch_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

Linear layer in pytorch

In [0]:
from torch.nn import Linear
myLayer = Linear(in_features = 10,out_features = 5,bias = True)

In [3]:
from torch.autograd import Variable
inp = Variable(torch.randn(1,10))
myLayer(inp)

tensor([[ 0.0757,  0.8960, -0.0585, -0.5007,  0.0877]],
       grad_fn=<AddmmBackward>)

In [5]:
myLayer.weight

Parameter containing:
tensor([[ 0.2612,  0.0577,  0.1915,  0.3013,  0.2970, -0.1300,  0.0545,  0.1860,
         -0.0154,  0.2400],
        [-0.2169, -0.0064,  0.0491,  0.0959, -0.1027,  0.0590,  0.1906, -0.1599,
         -0.0371, -0.0329],
        [ 0.0009,  0.0072,  0.2838,  0.2365,  0.3143, -0.2558, -0.2941,  0.0910,
         -0.2651,  0.0401],
        [ 0.1820, -0.0487, -0.1253,  0.1803, -0.2319,  0.1408, -0.2264, -0.3080,
         -0.2448,  0.0209],
        [ 0.2134,  0.0581, -0.1510,  0.2163, -0.0519, -0.0933, -0.0982,  0.2841,
         -0.2346,  0.2478]], requires_grad=True)

In [6]:
myLayer.bias

Parameter containing:
tensor([-0.2997,  0.1569,  0.2140, -0.0293,  0.2281], requires_grad=True)

Layers can be stacked

In [7]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[-0.7350,  0.3748]], grad_fn=<AddmmBackward>)

Non linear layers

Relu

In [9]:
from torch.nn import ReLU
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
myrelu = ReLU()
myrelu(sample_data)

tensor([[1., 2., 0., 0.]])

The pytorch way of building neural networks

In [0]:
from torch import nn
class MyFirstNetwork(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(MyFirstNetwork,self).__init__()
    self.layer1 = Linear(input_size,hidden_size)
    self.layer2 = Linear(hidden_size,output_size)
  def __forward__(self,input):
    out = self.layer1(input)
    out = self.ReLU(out)
    out = self.layer2(out)
    return out

Loss function MSELoss

In [0]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5),requires_grad = True)
target = Variable(torch.randn(3,5))
output = loss(input,target)
output.backward()

how crossentropy loss works

In [0]:
def cross_entropy(true_label,prediction):
  if true_label == 1:
    return -log(prediction)
  else:
    return -log(1 - prediction)

pytorch's implementation of crossentropy loss

In [0]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5),requires_grad = True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input,target)
output.backward()



> Loss types


1.   L1 loss (mostly used as reguralizer)
2.   MSELoss (used for regression)
3.   Cross-entropyloss (used for binary and multiclassification problems
4.   NLL Loss (used for classification problems and allows us to use specific weights for imbalenced datasets)
5.   NLL Loss2d (used for pixel wise classfication, mostly used for image segmentation)







> Some of the pytorch optimizers


*   ADADELTA
*   Adagrad
*   Adam
*   SparseAdam
*   Adamax
*   ASGD
*   LBFGS
*   RMSProp
*   Rprop
*   SGD





Creating optimizer

In [0]:
optimizer = optim.SGD(model.parameters(),lr = 0.01)

Training neural network

In [0]:
for input,target in dataset:
  optimizer.zero_grad()
  output = model(input)
  loss = loss_fn(output,target)
  loss.backward()
  optimizer.step()

Follow up is cats vs dogs notebook in which learned knowledge is implemented.