<a href="https://colab.research.google.com/github/narsym/deep-learning-with-pytorch/blob/master/pytorch_again.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#pytorch introduction

In [4]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

True
tensor([[0.9008, 0.5137],
        [0.5342, 0.2141]])


Creating tensors from lists

In [2]:
x = torch.tensor([[0,1,0],[1,0,0],[0,0,1]])
x

tensor([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])

Changing values in tensor

In [3]:
x[0][0] = 5
x

tensor([[5, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])

Special creation functions to generate particular type of tensors

In [4]:
y = torch.ones(1,2)
z = torch.zeros(1,2)

In [5]:
print(y,z)

tensor([[1., 1.]]) tensor([[0., 0.]])


Mathematical operations on tensors

In [6]:
y + z

tensor([[1., 1.]])

getting value of the tensor of rank 0 using item() function

In [9]:
a = torch.rand(1)
a.item()

0.8993659615516663

Tensors can live on the cpu or on the gpu, can be copied between devices using to() function

In [5]:
cpu_tensor = torch.rand([2,2])
cpu_tensor.device

device(type='cpu')

In [6]:
gpu_tensor = cpu_tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

some useful functions

In [7]:
torch.rand([2,2]).max() # to get max value

tensor(0.7731)

In [8]:
torch.rand([2,2]).max().item() # to get max value in python value format

0.7372029423713684

In [10]:
torch.rand([2,2]).argmax().item() # to get the index of the max value in the tensor

0

Change the tensor type

In [11]:
long_tensor = torch.tensor([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
long_tensor.type()

'torch.LongTensor'

In [12]:
float_tensor = long_tensor.to(dtype = torch.float32)
float_tensor.type()

'torch.FloatTensor'

tensor operations create new tensors and return them to save memory write to the original space allocated using '_' before parenthesis in the function. Should be useful for the most of the functions.

In [14]:
random_tensor = torch.rand([2,2])
random_tensor.log2()

tensor([[-1.2649, -0.1571],
        [-2.6169, -2.6380]])

In [15]:
random_tensor #original tensor not changed

tensor([[0.4161, 0.8968],
        [0.1630, 0.1607]])

In [17]:
random_tensor.log2_()

tensor([[-1.2649, -0.1571],
        [-2.6169, -2.6380]])

In [18]:
random_tensor #now original tensor changed

tensor([[-1.2649, -0.1571],
        [-2.6169, -2.6380]])

Shaping the tensor using view() and reshape() functions

In [23]:
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [24]:
reshaped_tensor = flat_tensor.reshape(1, 28, 28) # always use this
reshaped_tensor.shape

torch.Size([1, 28, 28])

permute to change the dimensions of the tensor

In [25]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])

TensorBroadcasting

In [26]:
x = torch.rand(1, 3)
y = torch.rand(3, 3)
x + y

tensor([[0.7733, 1.4609, 1.3903],
        [1.1062, 1.0637, 0.5733],
        [0.5861, 1.0028, 0.8634]])